set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_SYSTEM_VERSION 1)

set(CMAKE_CROSSCOMPILING TRUE)
set(CMAKE_CROSSCOMPILING_EMULATOR qemu -cpu cascadelake -L /usr/${CMAKE_C_COMPILER_TARGET}/)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -march=cascadelake")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=cascadelake")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
