name: CMake
on: [push, pull_request]
env:
  TERM: xterm-256color
  GTEST_COLOR: 1
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  cmake:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu 20.04 GCC
            os: ubuntu-20.04
            compiler: gcc
            cxx-compiler: g++

          - name: Ubuntu GCC S390X DFLTCC ASAN
            os: ${{ (github.repository == 'zlib-ng/zlib-ng' && 'z15') || 'ubuntu-latest' }}
            compiler: gcc
            cxx-compiler: g++
            cmake-args: >-
              ${{ github.repository == 'zlib-ng/zlib-ng' && '' || '-DCMAKE_TOOLCHAIN_FILE=cmake/toolchain-s390x.cmake' }}
              -DWITH_DFLTCC_DEFLATE=ON -DWITH_DFLTCC_INFLATE=ON -DWITH_SANITIZER=Address
            packages: qemu qemu-user gcc-s390x-linux-gnu g++-s390x-linux-gnu libc-dev-s390x-cross
            asan-options: detect_leaks=0
            ldflags: -static
            codecov: ubuntu_gcc_s390x_dfltcc
            # The dedicated test VM has 4 cores
            parallels-jobs: 4

          - name: Ubuntu GCC S390X DFLTCC Compat UBSAN
            os: ${{ (github.repository == 'zlib-ng/zlib-ng' && 'z15') || 'ubuntu-latest' }}
            compiler: gcc
            cxx-compiler: g++
            cmake-args: >-
              ${{ github.repository == 'zlib-ng/zlib-ng' && '' || '-DCMAKE_TOOLCHAIN_FILE=cmake/toolchain-s390x.cmake' }}
              -DZLIB_COMPAT=ON -DWITH_DFLTCC_DEFLATE=ON -DWITH_DFLTCC_INFLATE=ON -DWITH_SANITIZER=Undefined
            packages: qemu qemu-user gcc-s390x-linux-gnu g++-s390x-linux-gnu libc-dev-s390x-cross
            ldflags: -static
            codecov: ubuntu_gcc_s390x_dfltcc_compat
            # The dedicated test VM has 4 cores
            parallels-jobs: 4

          - name: Ubuntu Clang S390X DFLTCC MSAN
            os: ${{ (github.repository == 'zlib-ng/zlib-ng' && 'z15') || 'ubuntu-latest' }}
            compiler: clang-11
            cxx-compiler: clang++-11
            cmake-args: >-
              ${{ github.repository == 'zlib-ng/zlib-ng' && '' || '-DCMAKE_TOOLCHAIN_FILE=cmake/toolchain-s390x.cmake' }}
              -GNinja -DWITH_DFLTCC_DEFLATE=ON -DWITH_DFLTCC_INFLATE=ON -DWITH_SANITIZER=Memory
            llvm-cmake-args: >-
              ${{ github.repository == 'zlib-ng/zlib-ng' && '' || '-DCMAKE_TOOLCHAIN_FILE=../../cmake/toolchain-s390x.cmake' }}
            packages: qemu qemu-user gcc-s390x-linux-gnu g++-s390x-linux-gnu libc-dev-s390x-cross
            ldflags: ${{ github.repository == 'zlib-ng/zlib-ng' && '-static' }}
            # The dedicated test VM has 4 cores
            parallels-jobs: 4

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        show-progress: 'false'

    - name: Checkout test corpora
      uses: actions/checkout@v4
      # Don't test against all corpora with MinGW due to Wine being unable to run parallel jobs
      # without connection timeout. Without parallel jobs test runs using Wine take close to an hour.
      if: contains(matrix.name, 'MinGW') == false
      with:
        repository: zlib-ng/corpora
        path: test/data/corpora
        show-progress: 'false'

    - name: Add repositories (Wine)
      if: contains(matrix.packages, 'wine32')
      run: sudo dpkg --add-architecture i386

    - name: Add ubuntu mirrors
      if: runner.os == 'Linux' && matrix.packages
      run: |
        # Github Actions caching proxy is at times unreliable
        echo -e 'http://azure.archive.ubuntu.com/ubuntu\tpriority:1\n' | sudo tee /etc/apt/mirrors.txt
        curl http://mirrors.ubuntu.com/mirrors.txt | sudo tee --append /etc/apt/mirrors.txt
        sudo sed -i 's#http://azure.archive.ubuntu.com/ubuntu/#mirror+file:/etc/apt/mirrors.txt#' /etc/apt/sources.list

    - name: Install packages (Ubuntu)
      if: runner.os == 'Linux' && matrix.packages
      run: |
        sudo apt-get update
        sudo apt-get install -y --allow-downgrades --no-install-recommends ${{ matrix.packages }}

    - name: Download prebuilt RISC-V Clang toolchain & QEMU emulator
      if: runner.os == 'Linux' && contains(matrix.name, 'RISC-V')
      run: |
        gh release download ubuntu20.04_llvm16.0.0_qemu7.0.0 --repo sifive/prepare-riscv-toolchain-qemu
        tar zxvf prebuilt-riscv-toolchain-qemu.tar.gz
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install packages (Windows)
      if: runner.os == 'Windows'
      run: |
        # strawberryperl installs /c/Strawberry/c/bin/libstdc++-6.dll, which is incompatible with the mingw64 one.
        # zlib-ng does not need perl, so simply remove it.
        choco uninstall --no-progress strawberryperl
        choco install --no-progress ninja ${{ matrix.packages }}

    - name: Install packages (macOS)
      if: runner.os == 'macOS'
      run: brew install ninja ${{ matrix.packages }}
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1

    - name: Install Emscripten
      if: contains(matrix.name, 'WASM32')
      uses: mymindstorm/setup-emsdk@v12

    - name: Initialize Wine
      # Prevent parallel test jobs from initializing Wine at the same time
      if: contains(matrix.packages, 'wine')
      run: wineboot --init

    - name: Compile LLVM C++ libraries (MSAN)
      if: contains(matrix.name, 'MSAN')
      run: |
        git clone --depth=1 https://github.com/llvm/llvm-project --single-branch --branch llvmorg-11.1.0
        cmake -S llvm-project/llvm -B llvm-project/build -G Ninja ${{ matrix.llvm-cmake-args }} \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_ENABLE_PROJECTS="libcxx;libcxxabi" \
          -DLLVM_USE_SANITIZER=MemoryWithOrigins \
          -DLLVM_LIBC_ENABLE_LINTING=OFF
        cmake --build llvm-project/build -j2 -- cxx cxxabi
        echo "LLVM_BUILD_DIR=`pwd`/llvm-project/build" >> $GITHUB_ENV
      env:
        CC: ${{ matrix.compiler }}
        CXX: ${{ matrix.cxx-compiler }}

    - name: Make source tree read-only
      shell: bash
      run: chmod -R a-w .
      if: matrix.readonly-project-dir

    - name: Generate project files
      shell: bash
      # Shared libraries turned off for qemu ppc* and sparc & reduce code coverage sources
      run: |
        cmake -S ${{ matrix.build-src-dir || '.' }} -B ${{ matrix.build-dir || '.' }} ${{ matrix.cmake-args }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build-config || 'Release' }} \
          -DBUILD_SHARED_LIBS=${{ matrix.build-shared || 'OFF' }} \
          -DWITH_FUZZERS=ON \
          -DWITH_MAINTAINER_WARNINGS=ON \
          ${{ matrix.codecov && '-DWITH_CODE_COVERAGE=ON' }}
      env:
        CC: ${{ matrix.compiler }}
        CXX: ${{ matrix.cxx-compiler }}
        CFLAGS: ${{ matrix.cflags }}
        LDFLAGS: ${{ matrix.ldflags }}
        CI: true

    - name: Compile source code
      run: cmake --build ${{ matrix.build-dir || '.' }} -j2 --config ${{ matrix.build-config || 'Release' }}

    - name: Run test cases
      # Don't run tests on Windows ARM
      if: runner.os != 'Windows' || contains(matrix.name, 'ARM') == false
      run: ctest --verbose -C Release --output-on-failure --max-width 120 -j ${{ matrix.parallels-jobs || '3' }}
      working-directory: ${{ matrix.build-dir || '.' }}
      env:
        ASAN_OPTIONS: ${{ matrix.asan-options || 'verbosity=0' }}:abort_on_error=1:halt_on_error=1
        MSAN_OPTIONS: ${{ matrix.msan-options || 'verbosity=0' }}:abort_on_error=1:halt_on_error=1
        TSAN_OPTIONS: ${{ matrix.tsan-options || 'verbosity=0' }}:abort_on_error=1:halt_on_error=1
        LSAN_OPTIONS: ${{ matrix.lsan-options || 'verbosity=0' }}:abort_on_error=1:halt_on_error=1
        UBSAN_OPTIONS: ${{ matrix.ubsan-options || 'verbosity=0' }}:print_stacktrace=1:abort_on_error=1:halt_on_error=1

    - name: Make source tree writable
      shell: bash
      run: chmod -R +w .
      if: matrix.readonly-project-dir

    - name: Generate coverage report
      if: matrix.codecov
      shell: bash
      run: |
        python3 -u -m pip install --user gcovr==5.0
        python3 -m gcovr -j 3 --verbose \
          --exclude-unreachable-branches \
          --gcov-executable "${{ matrix.gcov-exec || 'gcov' }}" \
          --root ${{ matrix.build-src-dir || '.' }} \
          --xml --output ${{ matrix.codecov }}.xml

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v3
      if: matrix.codecov
      with:
        path: ${{ matrix.codecov }}.xml
        retention-days: 1

    - name: Upload build errors
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: ${{ matrix.name }} (cmake)
        path: |
          **/CMakeFiles/CMakeOutput.log
          **/CMakeFiles/CMakeError.log
          **/Testing/Temporary/*
          coverage.xml
        retention-days: 30

  coverage:
    name: Upload Coverage Reports
    runs-on: ubuntu-latest
    needs: cmake
    steps:
    - name: Download all reports
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true

    - name: Display structure of downloaded files
      run: ls -R

    - name: Upload reports
      uses: codecov/codecov-action@v3
      #if: (env.CODECOV_TOKEN != '' || github.repository == 'zlib-ng/zlib-ng')
      with:
        token: ${{ secrets.CODECOV_TOKEN || 'e4fdf847-f541-4ab1-9d50-3d27e5913906' }}
        verbose: true
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: "${{secrets.CODECOV_TOKEN}}"
